language: go

go:
  - "1.11.x"

script:
  - go build
  - go fmt ./...
  - go vet ./...
  - go test -coverprofile=coverage.txt -covermode=atomic -race -v ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
