language: go

go:
  - "1.14.x"

script:
  - go get .
  - go mod verify
  - go fmt ./...
  - go test -coverprofile=coverage.txt -covermode=atomic -race -v ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
