language: go

go:
  - 1.6

script:
  - go build
  - go fmt ./...
  - go vet ./...
  - go test -race -v ./...
  - ./ntimes -n 10 bash -c 'sleep=$((RANDOM%5)); fail=$((RANDOM%2)); echo "id=$NTIMES_ID, sleep=$sleep, fail=$fail"; sleep $sleep; exit $fail'
  - ./ntimes --format "{{json .}}" -n 10 dd if=/dev/urandom of=/dev/null bs=512 count=1000
  - ./ntimes --version
